name: Update recent artists in README

on:
  schedule:
    - cron: "5 * * * *"

jobs:
  run:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false
        fetch-depth: 0
    
    - uses: actions/setup-node@v2.1.0
      with:
        node-version: '14'
        
    - run: npm install
    - run: npm run get-recently-played
    - run: |
        git commit -am "(action) update recent artists"
        git push
