name: Update recent artists in README

on:
  push:
    branches: 
      - master
  schedule:
    - cron: "0 0 * * *"

jobs:
  run:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - uses: actions/setup-node@v2.1.0
      with:
        node-version: '14'
        
    - run: npm install
    - run: npm run get-recently-played
    - run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git commit -am "(action) update recent artists" || echo "No changes to commit"
        git push
    env:
      SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
      SPOTIFY_CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
      SPOTIFY_ACCESS_TOKEN: ${{ secrets.SPOTIFY_ACCESS_TOKEN }}
      SPOTIFY_REFRESH_TOKEN: ${{ secrets.SPOTIFY_REFRESH_TOKEN }}
